## Data root
data_type: &data_type cardiac_cine
data_type_ntw: 7
data_root: !join [workspace_data/]
results_root: !join [workspace_results/]

# recon config
nx: 416
ny: 416
final_shape: 104
nnav: 25
cycle_duration: 1
coord_dim: 3 # and for second network +1 (t)

## Training
optimizer:
  module: Adam
  params:
    lr: 1e-5
    amsgrad: True
#    weight_decay: 0.01
#    momentum: 0
#    betas: [0.95, 0.999]

## Dataset
dataset:
  module: datasets.radialSoS_sorted
  name: RadialSoSDataset
  nav_min: 0.0
  nav_max: 1.0
  nav_drift: False
  fe_crop: 1.0     # crop the FE range (resolution is decreased)
  fe_oversampling: 1 # if >1, removes the fe_oversampling
  acc_factor: 1     # cut spokes
  scale_coils: False
  remove_center: False
num_workers: 0
sample_spoke: True
random_sample: False

